-- Supabase FULL Backup - HealthyCommunityMonitoring
-- Generated on: 2026-03-29
-- Project ID: ehbaenczvnphgiuwujoc

-------------------------------------------------------
-- 1. FUNCTIONS DEFINITIONS
-------------------------------------------------------

-- create_report_history
CREATE OR REPLACE FUNCTION public.create_report_history()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
INSERT INTO report_history (
    report_id,
    report_status,
    created_at
)
VALUES (
    NEW.report_id,
    'new',
    NOW()
);
RETURN NEW;
END;
$function$;

-- get_confirmed_reports
CREATE OR REPLACE FUNCTION public.get_confirmed_reports()
 RETURNS TABLE(report_id bigint, disease_name text, governorate_name text, report_date timestamp with time zone, lat double precision, lng double precision)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  WITH latest_history AS (
    SELECT DISTINCT ON (h.report_id) 
      h.report_id, 
      h.disease_id
    FROM public.report_history h
    WHERE h.disease_id IS NOT NULL
    ORDER BY h.report_id, h.created_at DESC
  )
  SELECT 
    r.report_id,
    COALESCE(d_hist.disease_name, d_init.disease_name) as disease_name,
    g.governorate_name,
    r.report_date,
    st_y(r.location) as lat,
    st_x(r.location) as lng
  FROM public.report r
  LEFT JOIN latest_history lh ON r.report_id = lh.report_id
  LEFT JOIN public.disease d_hist ON lh.disease_id = d_hist.disease_id
  LEFT JOIN public.disease d_init ON r.disease_id = d_init.disease_id
  LEFT JOIN public.governorate g ON r.governorate_id = g.governorate_id
  WHERE r.classification_id = 3;
END;
$function$;

-- generate_tracking_number
CREATE OR REPLACE FUNCTION public.generate_tracking_number()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.tracking_number IS NULL THEN
        NEW.tracking_number := 'RPT-' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT), 1, 6));
    END IF;
    RETURN NEW;
END;
$function$;

-- find_governorate
CREATE OR REPLACE FUNCTION public.find_governorate()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    SELECT g.governorate_id INTO NEW.governorate_id
    FROM governorate g
    WHERE ST_Contains(g.geom, NEW.location)
      AND g.governorate_id != 13
    LIMIT 1;
    
    IF NEW.governorate_id IS NULL THEN
        NEW.governorate_id := 13;
    END IF;

    RETURN NEW;
END;
$function$;

-- classify_report_disease
CREATE OR REPLACE FUNCTION public.classify_report_disease()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
UPDATE report_history rh
SET disease_id = (
    SELECT ds.disease_id
    FROM disease_symptom ds
    JOIN symptom_report sr 
         ON sr.symptom_id = ds.symptom_id
    WHERE sr.report_id = NEW.report_id
    GROUP BY ds.disease_id
    ORDER BY SUM(ds.weight) DESC
    LIMIT 1
)
WHERE rh.report_id = NEW.report_id;
RETURN NEW;
END;
$function$;

-- check_disease_threshold
CREATE OR REPLACE FUNCTION public.check_disease_threshold()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_report_count INTEGER;
    v_threshold INTEGER;
    v_disease_name TEXT;
BEGIN
    SELECT threshold, disease_name
    INTO v_threshold, v_disease_name
    FROM disease
    WHERE disease_id = NEW.disease_id;

    SELECT COUNT(*)
    INTO v_report_count
    FROM report_history
    WHERE disease_id = NEW.disease_id
      AND created_at >= NOW() - INTERVAL '1 hour';

    IF v_report_count >= v_threshold THEN
        IF NOT EXISTS (
            SELECT 1 FROM notification
            WHERE disease_id = NEW.disease_id
              AND created_at >= NOW() - INTERVAL '1 hour'
        ) THEN
            INSERT INTO notification (disease_id, message, created_at)
            VALUES (
                NEW.disease_id,
                '🚨 تنبيه: تم تجاوز الحد المسموح لمرض "' || v_disease_name || '" حيث تم تسجيل ' || v_report_count || ' بلاغاً خلال الساعة الأخيرة.',
                NOW()
            );
        END IF;
    END IF;

    RETURN NEW;
END;
$function$;

-------------------------------------------------------
-- 2. SCHEMA DEFINITION (Tables)
-------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_role (
    role_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user (
    user_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name text,
    password text,
    phone text UNIQUE,
    created_at timestamp with time zone DEFAULT now(),
    role_id bigint DEFAULT '3'::bigint REFERENCES public.user_role(role_id),
    email varchar
);

CREATE TABLE IF NOT EXISTS public.governorate (
    governorate_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    governorate_name text UNIQUE NOT NULL,
    user_id bigint REFERENCES public.user(user_id),
    geom geometry
);

CREATE TABLE IF NOT EXISTS public.disease (
    disease_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    disease_name text UNIQUE NOT NULL,
    user_id bigint REFERENCES public.user(user_id),
    threshold bigint DEFAULT '1'::bigint
);

CREATE TABLE IF NOT EXISTS public.symptom (
    symptom_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    symptom_name text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.report_classification (
    classification_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    case_classification text UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS public.report (
    report_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    patient_name text,
    age bigint,
    location geometry,
    notes text,
    onset_date timestamp with time zone,
    report_date timestamp with time zone DEFAULT now(),
    phone text,
    gender text,
    governorate_id bigint REFERENCES public.governorate(governorate_id),
    user_id bigint REFERENCES public.user(user_id),
    classification_id bigint DEFAULT '5'::bigint REFERENCES public.report_classification(classification_id),
    disease_id bigint REFERENCES public.disease(disease_id),
    tracking_number varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS public.report_history (
    report_id bigint REFERENCES public.report(report_id),
    report_status text DEFAULT 'new'::text,
    updated_user_id bigint REFERENCES public.user(user_id),
    created_at timestamp with time zone DEFAULT now(),
    disease_id integer,
    PRIMARY KEY (report_id, created_at)
);

CREATE TABLE IF NOT EXISTS public.symptom_report (
    symptom_id bigint REFERENCES public.symptom(symptom_id),
    report_id bigint REFERENCES public.report(report_id),
    PRIMARY KEY (symptom_id, report_id)
);

CREATE TABLE IF NOT EXISTS public.news (
    item_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    type text,
    content text,
    publish_date timestamp with time zone DEFAULT now(),
    created_by bigint REFERENCES public.user(user_id),
    image text
);

CREATE TABLE IF NOT EXISTS public.notification (
    notification_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    disease_id integer REFERENCES public.disease(disease_id),
    message text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.disease_symptom (
    disease_id integer REFERENCES public.disease(disease_id),
    symptom_id integer REFERENCES public.symptom(symptom_id),
    weight numeric,
    PRIMARY KEY (disease_id, symptom_id)
);

-------------------------------------------------------
-- 3. TRIGGERS
-------------------------------------------------------

CREATE TRIGGER trg_find_governorate BEFORE INSERT OR UPDATE ON public.report FOR EACH ROW EXECUTE FUNCTION find_governorate();
CREATE TRIGGER trg_classify_disease AFTER INSERT ON public.symptom_report FOR EACH ROW EXECUTE FUNCTION classify_report_disease();
CREATE TRIGGER trg_create_report_history AFTER INSERT ON public.report FOR EACH ROW EXECUTE FUNCTION create_report_history();
CREATE TRIGGER trigger_check_disease AFTER INSERT OR UPDATE ON public.report_history FOR EACH ROW EXECUTE FUNCTION check_disease_threshold();
CREATE TRIGGER trg_generate_tracking_number BEFORE INSERT ON public.report FOR EACH ROW EXECUTE FUNCTION generate_tracking_number();

-------------------------------------------------------
-- 4. DATA (Key Sample)
-------------------------------------------------------

INSERT INTO public.user_role (role_name) VALUES ('admin'), ('editor'), ('user') ON CONFLICT DO NOTHING;
INSERT INTO public.user (user_id, full_name, password, phone, created_at, role_id, email) VALUES
(2, 'noor', '123', '12345', '2026-02-12', 3, NULL),
(10, 'noor alattas', '123456', '+967773030262', '2026-03-14', 3, 'nalattas2026@gmail.com')
ON CONFLICT (user_id) DO NOTHING;
